code --install-extension golang.go
code --install-extension ms-azuretools.vscode-docker
code --install-extension mhutchie.git-graph
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension redhat.vscode-yaml
code --install-extension mechatroner.rainbow-csv
code --install-extension TabNine.tabnine-vscode
code --install-extension usernamehw.errorlens
code --install-extension PKief.material-icon-theme
code --install-extension zhuangtongfa.Material-theme
code --install-extension quicktype.quicktype
code --install-extension esbenp.prettier-vscode
code --install-extension alefragnani.Bookmarks
code --install-extension formulahendry.code-runner
code --install-extension eamodio.gitlens
code --install-extension yokoe.vscode-postfix-go
code --install-extension zxh404.vscode-proto3